/// <summary>
/// Defines the Transaction Results
/// </summary>
namespace XentePaymentSDK
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Transaction Response Results
    /// </summary>
    public class TransactionDetailsResponse
    {
        /// <summary>
        /// Set or Get status message
        /// </summary>

        [JsonPropertyAttribute("message")]
        public string Message { get; set; }
        /// <summary>
        /// Get or Set the status code
        /// </summary>

        [JsonProperty("code")]
        public int Code { get; set; }
        /// <summary>
        /// Get or set data about the transaction Results
        /// </summary>

        [JsonProperty("data")]
        public TransactionDetailsResponseData Data { get; set; }

        /// <summary>
        /// correlation ID
        /// </summary>
        [JsonProperty("correlationId")]
        public string CorrelationId { get; set; }
    }

    public class TransactionDetailsResponseData
    {
        /// <summary>
        /// Transaction ID generated by Xente for each transaction
        /// </summary>y>
        [JsonProperty("transactionId")]
        public string TransactionId { get; set; }

        [JsonProperty("requestReference")]
        public string RequestReference { get; set; }


        /// <summary>
        /// Batch ID for a particular collection or batch
        /// </summary>
        [JsonProperty("batchId")]
        public string BatchId { get; set; }

        /// <summary>
        /// The product which is being paid for
        /// </summary>
        [JsonProperty("product")]
        public string Product { get; set; }

        /// <summary>
        /// The payment provider 
        /// </summary>
        [JsonProperty("provider")]
        public string Provider { get; set; }

        /// <summary>
        /// The memo is the message describing the transaction
        /// </summary>
        [JsonProperty("memo")]
        public string Memo { get; set; }

        /// <summary>
        /// This is whether it is credit or debit transaction
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }

        /// <summary>
        /// The status of the transaction
        /// </summary>
        [JsonProperty("status")]
        public string Status { get; set; }

        /// <summary>
        /// The tells the user about the current status of the transaction
        /// </summary>
        [JsonProperty("statusMessage")]
        public string StatusMessage { get; set; }

        /// <summary>
        /// The amount of money under transaction
        /// </summary>
        [JsonProperty("amount")]
        public string Amount{ get; set; }

        /// <summary>
        /// The fee that is charged for the transaction made
        /// </summary>
        [JsonProperty("fee")]
        public string Fee { get; set; }

        /// <summary>
        /// The unique identifier for the customer in the payment collector site
        /// </summary>
        [JsonProperty("customerId")]
        public string CustomerId { get; set; }

        /// <summary>
        /// The date at which the transaction is created
        /// </summary>
        [JsonProperty("createdOn")]
        public string CreatedOn { get; set; }

        /// <summary>
        /// The date at which the transaction is modified
        /// </summary>
        [JsonProperty("modifiedOn")]
        public string ModifiedOn { get; set; }
    }
}
